// Mocks generated by Mockito 5.3.2 from annotations
// in gestion_bufete_app/test/features/gestion_bufete/data/repository/contrato_bufete_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gestion_bufete_app/src/features/gestion_bufete/data/datasource/local/contrato_bufete_local_datasource.dart'
    as _i2;
import 'package:gestion_bufete_app/src/features/gestion_bufete/data/models/contrato_model.dart'
    as _i4;
import 'package:gestion_bufete_app/src/features/gestion_bufete/domain/entities/contrato.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ContratoBufeteLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockContratoBufeteLocalDatasource extends _i1.Mock
    implements _i2.ContratoBufeteLocalDatasource {
  MockContratoBufeteLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> addContratoBufete(_i4.ContratoModel? newContrato) =>
      (super.noSuchMethod(
        Invocation.method(
          #addContratoBufete,
          [newContrato],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> editContratoBufete(
    int? key,
    _i4.ContratoModel? contrato,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editContratoBufete,
          [
            key,
            contrato,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> deleteContratoBufete(int? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteContratoBufete,
          [key],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<Map<dynamic, _i5.Contrato>> getAllContratoMes(String? mes) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllContratoMes,
          [mes],
        ),
        returnValue: _i3.Future<Map<dynamic, _i5.Contrato>>.value(
            <dynamic, _i5.Contrato>{}),
      ) as _i3.Future<Map<dynamic, _i5.Contrato>>);
  @override
  _i3.Future<double> getSaldoMes(String? mes) => (super.noSuchMethod(
        Invocation.method(
          #getSaldoMes,
          [mes],
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);
}
